### ISSUE TITLE
Project Demo?

### ISSUE THREAD

**Issue by whitef0x0** [anubiann00b/ModernTalk#1]
Would be great if there was a hosted demo or screenshot

**Comment by anubiann00b** [comment]
Whoops forgot to mention this is WIP (I haven't even started yet). Probably will work on it at CodeDay but otherwise this is going to be on the backburner for another month ish. I was inspired by the Slate article in the readme, and got started with envisioning what it'd look like and how it'd work.

Here's a screenshot of my current progress. It's just following the Scala.js getting started guide.

![image](https://cloud.githubusercontent.com/assets/5544386/15233709/ca8ff866-185f-11e6-89d8-dfb2b4ceea2c.png)
